# Generated by Django 5.0 on 2026-04-25 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0002_auditlog_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
